baseURL = 'https://hyoungjoojin.github.io/notes'
languageCode = 'en-us'
theme = 'typo'

[params]
home = "/notes"
title = "Hyoungjoo Jin's Notes"
colorPalette = 'base16-default'
hideHeader = true
showFooter = true
footerContent = "<p>Written by Hyoungjoo Jin."
math = true

[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "home"

[[params.social]]
name = "home"
url = "https://www.github.com/hyoungjoojin"

[[params.social]]
name = "github"
url = "https://www.github.com/hyoungjoojin"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/hyoungjoojin"

[markup]
[markup.highlight]
style = 'solarized-dark'

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[caches]
[caches.images]
dir = ':cacheDir/images'

