baseURL = 'https://hyoungjoojin.github.io/ps'
languageCode = 'en-us'
theme = 'typo'

[taxonomies]
tag = 'tags'

[params]
home = "/ps"
colorPalette = 'base16-default'
hideHeader = true
showFooter = false

[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "home"

[[params.social]]
name = "github"
url = "https://www.github.com/hyoungjoojin"

[markup]
[markup.highlight]
style = 'solarized-dark'

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[caches]
[caches.images]
dir = ':cacheDir/images'
